apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "desktop.fullname" . }}
  labels:
    {{- include "desktop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "desktop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "desktop.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "desktop.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.ui.image }}:{{ .Values.ui.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
        {{- end }}
          ports:
            - name: http
              containerPort: 6080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
