{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "desktop.serviceAccountName" . }}
  labels:
{{ include "desktop.labels" . | nindent 4 }}
{{- end -}}
